import IconBack from '../assets/svg/back.svg';
import IconSearch from '../assets/svg/search.svg';
import IconAbout from '../assets/svg/about.svg';
import IconAdd from '../assets/svg/add.svg';
import IconAvatar from '../assets/svg/avatar.svg';
import IconBell from '../assets/svg/bell.svg';
import IconCanceLBorder from '../assets/svg/cancelBorder.svg';
import IconChat from '../assets/svg/chat.svg';
import IconCheck from '../assets/svg/check.svg';
import IconLogoApple from '../assets/svg/LogoApple.svg';
import IconMenu from '../assets/svg/menu.svg';
import IconMenuOrder from '../assets/svg/order.svg';
import IconOrderCancelled from '../assets/svg/ordercancelled.svg';
import IconShowPassword from '../assets/svg/showpassword.svg';
import IconHidePassword from '../assets/svg/hidepassword.svg';
import IconToggleSwitch from '../assets/svg/toggleswitchoff.svg';
import IconWaitOrder from '../assets/svg/waitorder.svg';
import IconWaitPickup from '../assets/svg/waitpickup.svg';
import IconWaitShipper from '../assets/svg/waitshipper.svg';
import IconDateofBirth from '../assets/svg/dateofbirth.svg';
import IconGender from '../assets/svg/gender.svg';
import IconProtect from '../assets/svg/protect.svg';
import IconProduct from '../assets/svg/product.svg';
import IconChange from '../assets/svg/change.svg';
import IconShoppingCart from '../assets/svg/shoppingcart.svg';
import IconShare from '../assets/svg/share.svg';
import IconHeart from '../assets/svg/heart.svg';
import IconHeartChecked from '../assets/svg/heartChecked.svg';

export class Icon {
    static BackSVG = IconBack;
    static SearchSVG = IconSearch;
    static AboutSVG = IconAbout;
    static AddSVG = IconAdd;
    static AvatarSVG = IconAvatar;
    static BellSVG = IconBell;
    static CanceLBorderSVG = IconCanceLBorder;
    static ChatSVG = IconChat;
    static CheckSVG = IconCheck;
    static LogoAppleSVG = IconLogoApple;
    static MenuSVG = IconMenu;
    static MenuOrderSVG = IconMenuOrder;
    static OrderCancelledSVG = IconOrderCancelled;
    static ShowPasswordSVG = IconShowPassword;
    static HidePasswordSVG = IconHidePassword;
    static ToggleSwitchSVG = IconToggleSwitch;
    static WaitOrderSVG = IconWaitOrder;
    static WaitPickupSVG = IconWaitPickup;
    static WaitShipperSVG = IconWaitShipper;
    static DateofBirthSVG = IconDateofBirth;
    static GenderSVG = IconGender;
    static ProtectSVG = IconProtect;
    static ProductSVG = IconProduct;
    static ChangeSVG = IconChange;
    static ShoppingCartSVG = IconShoppingCart;
    static ShareSVG = IconShare;
    static HeartSVG = IconHeart;
    static HeartCheckedSVG = IconHeartChecked;
    static HOME = require('../assets/images/house.png');
    static CART = require('../assets/images/cart.png');
    static CATEGORY = require('../assets/images/category.png');
    static INFOR = require('../assets/images/infor.png');
    static RIGHT = require('../assets/images/right.png');
    static LOYALCUSTOMER = require('../assets/images/customervip.png');
    static PROFILE = require('../assets/images/profile.png');
    static ADDRESS = require('../assets/images/address.png');
    static FAVOURITE = require('../assets/images/favourite.png');
    static CHANGEPASSWORD = require('../assets/images/changepassword.png');
    static FEEDBACK = require('../assets/images/feedback.png');
    static CHATWITHSHOP = require('../assets/images/chatwithshop.png');
    static DELETEUSER = require('../assets/images/deleteuser.png');
    static CONTACT = require('../assets/images/contact.png');
    static INTRODUCE = require('../assets/images/introduce.png');
    static LOGOUT = require('../assets/images/logout.png');
    static DELETEACCOUNT = require('../assets/images/deleteacount.jpg');
    static CALL = require('../assets/images/call.png');
    static WEBSITE = require('../assets/images/website.png');
    static CONTACTFEEDBACK = require('../assets/images/contactfeedback.png');
    static EMAIL = require('../assets/images/email.png');
    static BACKGROUNDSTORE = require('../assets/images/backgroundstore.png');
    static GOOGLE = require('../assets/images/google.png');
    static ZALO = require('../assets/images/zalo.png');
    static FACEBOOK = require('../assets/images/facebook.png');
    static CANCELSEARCH = require('../assets/images/canecelSearch.png');
    static NotFoundProduct = require('../assets/images/NotfoundProduct.png');
}



export const Lottie = {
    Loading: require('../assets/lottie/loading.json'),
}
